### ISSUE TITLE
observable-press breaks on the new Observable file attachements

### ISSUE THREAD

**Issue by Fil** [zzzev/observable-press#2]
https://zzzev.github.io/observable-press/ is broken since the file attachments landed, probably for all notebooks that are using @jashkenas/inputs;
for example see https://zzzev.github.io/observable-press/examples/simple/

The error message is 
```
inputs.js?v=3:5 Uncaught (in promise) TypeError: runtime.fileAttachments is not a function
    at define (inputs.js?v=3:5)
    at p.value (observable-press.js:1)
    at define (slit-scan-effect.js?v=3:74)
    at p.value (observable-press.js:1)
    at Module.ie (observable-press.js:1)
    at (index):4
```

cc: @jashkenas @observablehq

Ref.: https://talk.observablehq.com/t/file-attachments/2499/12

**Comment by zzzev** [comment]
Thank you for the PR; merged and fixed!
